with change permissions

diff --git a/.github/workflows/test-719.yml b/.github/workflows/test-719.yml
--- a/.github/workflows/test-719.yml
+++ b/.github/workflows/test-719.yml
@@ -12,10 +12,18 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+      - name: Ensure Sudo is Installed
+        run: |
+          if ! command -v sudo &> /dev/null; then
+            echo "sudo could not be found. Installing..."
+            apt-get update && apt-get install -y sudo
+          fi
       - name: Install Docker
         run: |
           apt-get update
           apt-get install -y docker.io
+      - name: Change ownership of /github/home
+        run: sudo chown -R $(whoami) /github/home
       - name: Setup Python
         uses: actions/setup-python@v5
         with:
