with permissions

diff --git a/.github/workflows/test-930-final.yml b/.github/workflows/test-930-final.yml
--- a/.github/workflows/test-930-final.yml
+++ b/.github/workflows/test-930-final.yml
@@ -5,72 +5,73 @@ on:
       - main
   workflow_dispatch:
 jobs:
-  # test1:
-  #   runs-on: ubuntu-22.04
-  #   container:
-  #     image: mcr.microsoft.com/devcontainers/python:1.1.15-3.8-bookworm
-  #     # env:
-  #     #   PIP_ROOT_USER_ACTION: ignore
-  #   strategy:
-  #     matrix:
-  #       python: [3.11.6]
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #     - name: Ensure Sudo is Installed
-  #       run: |
-  #         if ! command -v sudo &> /dev/null; then
-  #           echo "sudo could not be found. Installing..."
-  #           apt-get update && apt-get install -y sudo
-  #         fi
-  #     - name: Install lsb-release
-  #       run: |
-  #         apt-get update
-  #         apt-get install -y lsb-release
-  #     - name: Create /etc/lsb-release
-  #       run: |
-  #         echo "DISTRIB_RELEASE=22.04" | tee -a /etc/lsb-release
-  #     - name: Check ownership
-  #       run: ls -ld /github/home
-
-  #     - name: Change ownership of /github/home
-  #       run: sudo chown -R $(whoami) /github/home
-  #     - name: Check ownership
-  #       run: ls -ld /github/home
-
-  #     - name: Setup Python
-  #       uses: priya-kinthali/setup-python@test-930
-  #       with:
-  #         python-version: ${{ matrix.python }}
-
-  test2:
-    runs-on: self-hosted
+  test1:
+    runs-on: ubuntu-22.04
+    container:
+      image: mcr.microsoft.com/devcontainers/python:1.1.15-3.8-bookworm
+      # env:
+      #   PIP_ROOT_USER_ACTION: ignore
     strategy:
       matrix:
-        python: [3.12.3]
+        python: [3.11.6]
     steps:
       - uses: actions/checkout@v4
-
-      - name: Check pip cache permissions
-        run: ls -ld /home/azureuser
-
-      - name: Create test directory
+      - name: Ensure Sudo is Installed
         run: |
-          # mkdir /home/azureuser/test-dir
-          sudo chown root:root /home/azureuser
-          sudo chmod 755 /home/azureuser/
+          if ! command -v sudo &> /dev/null; then
+            echo "sudo could not be found. Installing..."
+            apt-get update && apt-get install -y sudo
+          fi
+      - name: Install lsb-release
+        run: |
+          apt-get update
+          apt-get install -y lsb-release
+      - name: Create /etc/lsb-release
+        run: |
+          echo "DISTRIB_RELEASE=22.04" | tee -a /etc/lsb-release
+      - name: Check ownership
+        run: ls -ld /github/home
+      - name: Give all permissions to the current user
+        run: sudo chmod -R 777 /github/home
 
-      - name: Check pip cache permissions
-        run: ls -ld /home/azureuser
-
-
+      # - name: Change ownership of /github/home
+      #   run: sudo chown -R $(whoami) /github/home
+      - name: Check ownership
+        run: ls -ld /github/home
 
       - name: Setup Python
         uses: actions/setup-python@v5
         with:
           python-version: ${{ matrix.python }}
 
-      - name: echo env
-        run: echo $PIP_ROOT_USER_ACTION
+  # test2:
+  #   runs-on: self-hosted
+  #   strategy:
+  #     matrix:
+  #       python: [3.12.3]
+  #   steps:
+  #     - uses: actions/checkout@v4
+
+  #     - name: Check pip cache permissions
+  #       run: ls -ld /home/azureuser
+
+  #     - name: Create test directory
+  #       run: |
+  #         # mkdir /home/azureuser/test-dir
+  #         sudo chown root:root /home/azureuser
+  #         sudo chmod 755 /home/azureuser/
+
+  #     - name: Check pip cache permissions
+  #       run: ls -ld /home/azureuser
+
+
+
+  #     - name: Setup Python
+  #       uses: actions/setup-python@v5
+  #       with:
+  #         python-version: ${{ matrix.python }}
+
+
           # cache: 'pip'
           # cache-dependency-path: 'requirements.txt'
       # - name: Install Docker
