with image ubuntu and without cache

diff --git a/.github/workflows/test-930-final.yml b/.github/workflows/test-930-final.yml
--- a/.github/workflows/test-930-final.yml
+++ b/.github/workflows/test-930-final.yml
@@ -14,23 +14,19 @@ jobs:
         python: [3.11.6]
     steps:
       - uses: actions/checkout@v4
-      - name: Install Docker
-        run: |
-          apt-get update
-          apt-get install -y docker.io
-      - name: Ensure Sudo is Installed
-        run: |
-          if ! command -v sudo &> /dev/null; then
-            echo "sudo could not be found. Installing..."
-            apt-get update && apt-get install -y sudo
-          fi
-      - name: Install lsb-release
-        run: |
-          apt-get update
-          apt-get install -y lsb-release
-      - name: Create /etc/lsb-release
-        run: |
-          echo "DISTRIB_RELEASE=22.04" | tee -a /etc/lsb-release
+      # - name: Ensure Sudo is Installed
+      #   run: |
+      #     if ! command -v sudo &> /dev/null; then
+      #       echo "sudo could not be found. Installing..."
+      #       apt-get update && apt-get install -y sudo
+      #     fi
+      # - name: Install lsb-release
+      #   run: |
+      #     apt-get update
+      #     apt-get install -y lsb-release
+      # - name: Create /etc/lsb-release
+      #   run: |
+      #     echo "DISTRIB_RELEASE=22.04" | tee -a /etc/lsb-release
       # - name: fix pip issue
       #   run: |
             
@@ -45,3 +41,7 @@ jobs:
           python-version: ${{ matrix.python }}
           # cache: 'pip'
           # cache-dependency-path: 'requirements.txt'
+      # - name: Install Docker
+      #   run: |
+      #     apt-get update
+      #     apt-get install -y docker.io
