with env

diff --git a/.github/workflows/test-930.yml b/.github/workflows/test-930.yml
--- a/.github/workflows/test-930.yml
+++ b/.github/workflows/test-930.yml
@@ -11,10 +11,14 @@ jobs:
     runs-on: [self-hosted]
     steps:
 
-      - name: 	Clear cache
+      - name: Ensure Sudo is Installed
         run: |
-            mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
-            mkdir -p "${{ runner.tool_cache }}"
+          if ! command -v sudo &> /dev/null; then
+            echo "sudo could not be found. Installing..."
+            apt-get update && apt-get install -y sudo
+          fi
+      - name: Force delete directory
+        run: sudo rm -rf /home/azureuser/actions-runner/_work/test-samplepython/test-samplepython/.github/workflows
       - uses: actions/checkout@v4
      
       - name: Setup Python
