with env

diff --git a/.github/workflows/test-930-docker.yml b/.github/workflows/test-930-docker.yml
--- a/.github/workflows/test-930-docker.yml
+++ b/.github/workflows/test-930-docker.yml
@@ -35,12 +35,20 @@ jobs:
     
       - name: fix pip issue
         run: mkdir -p /github/home/.cache/pip
+      - name: Ensure Sudo is Installed
+        run: |
+          if ! command -v sudo &> /dev/null; then
+            echo "sudo could not be found. Installing..."
+            sudo apt-get update && sudo apt-get install -y sudo
+          fi
+      - name: Change ownership of /github/home
+        run: sudo chown -R $(whoami) /github/home
      
      
       - name: Setup Python
         uses: actions/setup-python@v5
         with:
-          python-version: "3.10.13"
+          python-version: "3.10.12"
           cache: 'pip'
           cache-dependency-path: 'requirements.txt'
       
